// <auto-generated />
using GameFinder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameFinder.Migrations
{
    [DbContext(typeof(GameFinderContext))]
    [Migration("20191028204526_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GameFinder.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvgPlayTime");

                    b.Property<int>("MaxPlayers");

                    b.Property<int>("MinAge");

                    b.Property<int>("MinPlayers");

                    b.Property<string>("Name");

                    b.Property<string>("Publisher");

                    b.Property<string>("Type");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            AvgPlayTime = 50,
                            MaxPlayers = 4,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Scrabble",
                            Publisher = "Hasbro",
                            Type = "Board"
                        },
                        new
                        {
                            GameId = 2,
                            AvgPlayTime = 30,
                            MaxPlayers = 2,
                            MinAge = 6,
                            MinPlayers = 2,
                            Name = "Chess",
                            Publisher = "None",
                            Type = "Strategy"
                        },
                        new
                        {
                            GameId = 3,
                            AvgPlayTime = 200,
                            MaxPlayers = 10,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Monopoly",
                            Publisher = "Hasbro",
                            Type = "Board"
                        },
                        new
                        {
                            GameId = 4,
                            AvgPlayTime = 80,
                            MaxPlayers = 6,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Trivial Pursuit",
                            Publisher = "Hasbro",
                            Type = "Board"
                        },
                        new
                        {
                            GameId = 5,
                            AvgPlayTime = 60,
                            MaxPlayers = 2,
                            MinAge = 2,
                            MinPlayers = 2,
                            Name = "Backgammon",
                            Publisher = "None",
                            Type = "Strategy"
                        },
                        new
                        {
                            GameId = 6,
                            AvgPlayTime = 10,
                            MaxPlayers = 15,
                            MinAge = 6,
                            MinPlayers = 1,
                            Name = "Jenga",
                            Publisher = "Hasbro",
                            Type = "Physical Skill"
                        },
                        new
                        {
                            GameId = 7,
                            AvgPlayTime = 10,
                            MaxPlayers = 4,
                            MinAge = 6,
                            MinPlayers = 4,
                            Name = "Twister",
                            Publisher = "Milton Bradley",
                            Type = "Physical Skill"
                        },
                        new
                        {
                            GameId = 8,
                            AvgPlayTime = 120,
                            MaxPlayers = 5,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Ticket to Ride",
                            Publisher = "Days of Wonder",
                            Type = "Board"
                        },
                        new
                        {
                            GameId = 9,
                            AvgPlayTime = 10,
                            MaxPlayers = 5,
                            MinAge = 6,
                            MinPlayers = 1,
                            Name = "Operation",
                            Publisher = "Hasbro",
                            Type = "Physical Skill"
                        },
                        new
                        {
                            GameId = 10,
                            AvgPlayTime = 360,
                            MaxPlayers = 6,
                            MinAge = 6,
                            MinPlayers = 2,
                            Name = "Risk",
                            Publisher = "Hasbro",
                            Type = "Strategy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
